jobs:
  retrieve-secret:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Retrieve secret from Vault
        uses: hashicorp/vault-action@v2.4.3
          with:
            exportToken: true
            method: jwt
            url: ${{ secrets.VAULT_ADDR }}
            role: github-actions
            secrets: |
              kv/main/message/text | MESSAGE_TEXT
              kv/main/message/lang | MESSAGE_LANG

      - name: Use secret from Vault
        run: |
          env | sort
          cat <<EOF
          ====
          MESSAGE_TEXT: ${steps.secrets.outputs.MESSAGE_TEXT}
          MESSAGE_LANG: ${steps.secrets.outputs.MESSAGE_LANG}
          EOF

      - name: Revoke token
        if: always()
        run: |
          curl -X POST -sv -H "X-Vault-Token: ${{ env.VAULT_TOKEN }}" ${{ secrets.VAULT_ADDR }}/v1/auth/token/revoke-self
