name: retrieve-secret
on:
- push
- workflow_dispatch
jobs:
  retrieve-secret:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Import Secrets
      id: secrets
      uses: hashicorp/vault-action@v2.4.3
      with:
        exportToken: true
        exportEnv: true
        method: jwt
        url: ${{ secrets.VAULT_ADDR }}
        role: cicd
        secrets: |
          kv/data/cicd/message text | MESSAGE_TEXT ;
          kv/data/cicd/message user | MESSAGE_USER
    - name: Use Secrets
      run: |
        echo "MESSAGE_TEXT: ${MESSAGE_TEXT}"
        echo "MESSAGE_USER: ${MESSAGE_USER}
    - name: Revoke token
      if: always()
      run: |
        curl -X POST -s -H "X-Vault-Token: ${VAULT_TOKEN}" ${{ secrets.VAULT_ADDR }}/v1/auth/token/revoke-self
