name: retrieve-secret
on:
- push
- workflow_dispatch
jobs:
  retrieve-secret:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Retrieve secret from Vault
      id: secrets
      uses: hashicorp/vault-action@v2.4.3    
      with:
        exportToken: true
        exportEnv: true
        method: jwt
        url: ${{ secrets.VAULT_ADDR }}
        role: github-actions
        secrets: |
          kv/data/main/message text | MESSAGE_TEXT;
          kv/data/main/message user | MESSAGE_USER

    - name: Use secret from Vault
      run: |
        cat <<EOF
        ====
        MESSAGE_TEXT: ${MESSAGE_TEXT}
        MESSAGE_USER: ${MESSAGE_USER}
        EOF

    - name: Revoke token
      if: always()
      run: |
        curl -X POST -s -H "X-Vault-Token: ${VAULT_TOKEN}" ${{ secrets.VAULT_ADDR }}/v1/auth/token/revoke-self
